---
title: "My QMD Title"
author: "Your Name"
date: "2023-11-20"
---
### Which subcategory does this new page belong to?

Lab Practices

### Contents of New Page

Maybe I was

- Referencing
- the body text
- wring

Testing YAML Edit Stuff

- again

Does this now write over the previous file?

-  worked
- edit again as test

New Test

- test cat yml
project: 
  type: website
  
website: 
  title: "Ecosystem Assessment Lab Manual"
  navbar: 
    left: 
      - text: Home
        href: index.qmd
        icon: house-fill
        
      - text: Lab Practices
        href: Lab_Culture.qmd
        icon: people-fill
        
      - text: Projects
        icon: list-ol
        menu:
          - text: Florida Bay Juvenile Sportfish Sampling
            href: Test_Outside_File.qmd
          - text: South Florida Ecosystem Restoration Cruises FAKE
            href: body-in-qmd-save.qmd
          - text: Biscayne Bay Water Quality Sampling
        
        
  repo-actions:
    - edit
    - source
  repo-url: https://github.com/Ecosystem-Assessment-Lab/EAL_Lab_Manual

format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left

