---
title: "My QMD Title"
author: "Your Name"
date: "2023-11-20"
---
project: 
  type: website


website: 
  title: "Ecosystem Assessment Lab Manual"
  navbar: 
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Lab Culture"
        href: files_for_website/Lab_Culture.qmd
      - text: "Projects"
        menu:
          - files_for_website/Biscayne_Bay_Main.qmd
          - files_for_website/FL_Bay_Main.qmd
          - files_for_website/SFER_Main.qmd


  sidebar: 
    - title: "Projects"
      contents: 
        - section: files_for_website/Biscayne_Bay_Main.qmd
          contents:
            - files_for_website/HOLD_PG_BB.qmd
#End Biscayne Bay 

        - section: files_for_website/FL_Bay_Main.qmd
          contents: 
            - files_for_website/HOLD_PG_SF.qmd
#End FL Bay

        - section: files_for_website/SFER_Main.qmd
          contents:
            - files_for_website/HOLD_PG_SFER.qmd
#End SFER



format: 
  html: 
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
Does this ad a new page

- to the correct folder
- edit the quarto
