name: TEST Add Page to Lab Manual
description: Use this form to easily add a page to the Ecosystem Assessment Laboratory's Lab Manual.
title: "New_Page: "
labels: ["new_page"]
assignees: []
body:
    - type: dropdown
      id: project
      attributes:
         label: Which project does this new page belong to?
         options: 
            - Florida Bay Juvenile Sportfish Sampling
            - South Florida Ecosystem Restoration Cruises
            - Biscayne Bay Water Quality Sampling
            - TEST
         default: 0
         
    - type: textarea
      id: page_contents
      attributes: 
         label: Contents of New Page
         description: Please use the text editor to add the contents of the new page that you would like added to the lab manual.
         
