name: Create Quarto Page from Issue

on:
  issues:
    types: [opened, edited]
    
jobs:
  create-page:
    if: contains(github.event.issue.title, 'New_Page')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get issue Name
        id: get_issuename
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # Extract filename from the issue title after "New_Page: "
          FILENAME=$(echo "files_for_website/$(echo "${ISSUE_TITLE}" | sed -n 's/^New_Page: //p' | tr ' ' '-' | tr '[:upper:]' '[:lower:]').qmd")

          echo "FILENAME=${FILENAME}" >> $GITHUB_ENV
          
      - name: Find Project Name
        id: get_project
        run: |
          # Get the issue body
          issue_body="${{ github.event.issue.body }}"

          # Extract the desired line (adjust the line number as needed)
          get_proj=$(echo "$issue_body" | sed -n '3p')
          
          # Set the extracted line as an environment variable
          echo "PROJECT=$get_proj" >> $GITHUB_ENV
  
      - name: Edit Quarto File
        run: |
          if [ "${{ env.PROJECT }}" = "Florida Bay Juvenile Sportfish Sampling" ]; then
              awk -v filename="${{ env.FILENAME }}" 'index($0, "#End Biscayne Bay") {print "            - " filename}1' _quarto.yml > temp && mv temp _quarto.yml
          elif [ "${{ env.PROJECT }}" = "South Florida Ecosystem Restoration Cruises" ]; then
              awk -v filename="${{ env.FILENAME }}" 'index($0, "#End SFER") {print "            - " filename}1' _quarto.yml > temp && mv temp _quarto.yml
          elif [ "${{ env.PROJECT }}" = "Biscayne Bay Water Quality Sampling" ]; then
              awk -v filename="${{ env.FILENAME }}" 'index($0, "#End Biscayne Bay") {print "            - " filename}1' _quarto.yml > temp && mv temp _quarto.yml
          else
              # If no project matches, output a message
              echo "Project not recognized."
          fi
        


      - name: Create QMD File
        run: |
          echo "---" > "${{ env.FILENAME }}"
          echo "title: \"My QMD Title\"" >> "${{ env.FILENAME }}"
          echo "author: \"Your Name\"" >> "${{ env.FILENAME }}"
          echo "date: \"2023-11-20\"" >> "${{ env.FILENAME }}"
          echo "---" >> "${{ env.FILENAME }}"
          sed -n '7,$p' <<< "${{ github.event.issue.body }}" >> "${{ env.FILENAME }}"
          

          
      - name: Add and Commit Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Add new QMD file: ${{ env.FILENAME }}"
          git push origin HEAD
          
