name: Create Quarto Page from Issue

on:
  issues:
    types: [opened, edited]
    
jobs:
  create-page:
    if: contains(github.event.issue.title, 'New_Page')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get issue Name
        id: get_issuename
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # Extract filename from the issue title after "New_Page: "
          FILENAME=$(echo "${ISSUE_TITLE}" | sed -n 's/^New_Page: //p' | tr ' ' '-' | tr '[:upper:]' '[:lower:]').qmd
          echo "FILENAME=${FILENAME}" >> $GITHUB_ENV
          

      - name: Create QMD File
        run: |
          echo "---" > "${{ env.FILENAME }}"
          echo "title: \"My QMD Title\"" >> "${{ env.FILENAME }}"
          echo "author: \"Your Name\"" >> "${{ env.FILENAME }}"
          echo "date: \"2023-11-20\"" >> "${{ env.FILENAME }}"
          echo "---" >> "${{ env.FILENAME }}"
          sed -n '7,$p' <<< "${{ github.event.issue.body }}" > "${{ env.FILENAME }}"
          
      - name: Edit Quarto File
        run: |
          PROJECT= sed '3q;d' <<< "${{ github.event.issue.body }}"
          sed -i '/- text: ${PROJECT}/a\            href: ${{ env.FILENAME }}' _quarto.yml

          
      - name: Add and Commit Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add "${{ env.FILENAME }}"
          git commit -m "Add new QMD file: ${{ env.FILENAME }}"
          git push origin HEAD

