name: Create QMD from New Page Issue

on:
  issues:
    types: [opened]

jobs:
  create-qmd-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: extract-issue-info
        with:
          script: |
            const issueTitle = context.issue.title;
            const issueBody = context.issue.body;

            if (issueTitle.startsWith('New_Page:')) {
              // Extract filename from the title
              const filename = issueTitle.replace('New_Page:', '').trim().toLowerCase().replace(/\s+/g, '-');

              // Extract page content from the issue body (assuming it's in a field called 'page_contents')
              const pageContent = JSON.parse(issueBody).page_contents;

              core.setOutput('filename', filename);
              core.setOutput('pageContent', pageContent);
            }
      - name: Create QMD File
        if: steps.extract-issue-info.outputs.filename != ''
        run: |
          echo "---" > docs/${{ steps.extract-issue-info.outputs.filename }}.qmd
          echo "title: \"${{ steps.extract-issue-info.outputs.filename }}\"" >> docs/${{ steps.extract-issue-info.outputs.filename }}.qmd
          # Add other YAML front matter fields as needed
          echo "---" >> docs/${{ steps.extract-issue-info.outputs.filename }}.qmd
          echo "${{ steps.extract-issue-info.outputs.pageContent }}" >> docs/${{ steps.extract-issue-info.outputs.filename }}.qmd
